class HTTP_RESPONSE_CODE:
    #Default
    SUCCSESSFUL = 200
    ABORTED = 409
    INCORRECT_DATA = 413

    #CRUD operations
    SUCCESSFUL_CREATED = 201
    NO_ANY_PARAMETRS = 413
    ABORTED_CREATED = 413
    SUCCESSFUL_MODIFIED = 201
    ABORTED_MODIFIED = 413
    SUCCESSFUL_DELEATED = 204
    ABORTED_DELEATED = 417

    #mail
    SUCCESSFUL_SENT = 204
    ABORTED_SENT = 411

    #On login
    ACCESS_DENIED = 401
    INCORRECT_LOGIN = 419
    INCORRECT_PASSWORD = 419

    #JWT token
    JWT_TOKEN_IS_VALID = 204
    JWT_TOKEN_NOT_VALID = 423

    #Refresh token
    REFRESH_TOKEN_NOT_EXIST = 427
    REFRESH_TOKEN_NOT_VALID = 431
